### ISSUE TITLE
My deposit is not going through for hours

### ISSUE THREAD

**Issue by SeohoLee** [sologenic/deprecated-sologenic-expo-wallet#680]
Hello there

I made a transaction of xrp from bitrue to
Solo dex but the deposit is not going through.
Transaction record shows that it received but
it doesn’t show on my balance. Please advice.
Thank you.
![IMG_7941](https://github.com/user-attachments/assets/01420ccc-6cfa-4549-a024-aefb23db667f)

**Comment by consensys-mod** [comment]
> Hello there
> 
> I made a transaction of xrp from bitrue to Solo dex but the deposit is not going through. Transaction record shows that it received but it doesn’t show on my balance. Please advice. Thank you. ![IMG_7941](https://private-user-images.githubusercontent.com/127208601/391525261-01420ccc-6cfa-4549-a024-aefb23db667f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzk0ODYsIm5iZiI6MTczMzEzOTE4NiwicGF0aCI6Ii8xMjcyMDg2MDEvMzkxNTI1MjYxLTAxNDIwY2NjLTZjZmEtNDU0OS1hMDI0LWFlZmIyM2RiNjY3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxMTMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTM4NTdkYmFhMWU2MGI1ODdhNjc2N2Q4NmY4YmRmMGYxMjY0Y2NhZGU5NjQxZmUyZjM4NGQ5ODAzZDdmNGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EpJCyGJB7BygXMLQCPWPNOTXo1qwoukYCw5sPZfkOFE)

Sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Sologenic Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***
